/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#5e4100",
        "inverse-primary": "#ffb3b5",
        "tertiary-fixed-dim": "#f0b8c3",
        "on-background": "#201a1a",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#271900",
        "surface-container-low": "#fef1f0",
        "outline-variant": "#d7c1c1",
        "primary-container": "#e5989b",
        "primary": "#8b4c50",
        "surface-dim": "#e4d7d7",
        "surface-tint": "#8b4c50",
        "error-container": "#ffdad6",
        "on-surface": "#201a1a",
        "surface-container-high": "#f2e5e5",
        "on-primary": "#ffffff",
        "on-secondary-container": "#6b4b00",
        "error": "#ba1a1a",
        "on-surface-variant": "#524343",
        "tertiary-container": "#d49fa9",
        "surface-variant": "#ece0df",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffd9df",
        "surface-bright": "#fff8f7",
        "inverse-surface": "#362f2f",
        "secondary-container": "#ffb702",
        "surface-container": "#f8ebea",
        "surface-container-highest": "#ece0df",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#fbeeed",
        "background": "#fff8f7",
        "on-primary-fixed": "#380b10",
        "secondary": "#7d5800",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffba27",
        "primary-fixed": "#ffdada",
        "on-tertiary-container": "#5c353e",
        "secondary-fixed": "#ffdea9",
        "tertiary": "#7e525c",
        "primary-fixed-dim": "#ffb3b5",
        "on-primary-fixed-variant": "#6f3539",
        "surface": "#fff8f7",
        "on-tertiary-fixed": "#31111a",
        "outline": "#857373",
        "on-primary-container": "#672f33",
        "on-tertiary-fixed-variant": "#633b44",
      },
      borderRadius: {
        "blob-1": "60% 40% 30% 70% / 60% 30% 70% 40%",
        "blob-2": "40% 60% 70% 30% / 50% 60% 30% 50%",
        "blob-3": "70% 30% 50% 50% / 30% 30% 70% 70%",
      },
      spacing: {
        "content-gap": "24px",
        "dock-offset": "32px",
        "container-max": "1100px",
        "section-padding": "80px",
        "unit": "8px",
      },
      fontFamily: {
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
